angular.module('app').factory('currentSessionData', function () {
    return {
        cookies: [
            {"class": "bq-ok", "id": "ok", "name": "OK"},
            {"class": "bq-buhao", "id": "buhao", "name": "不好"},
            {"class": "bq-zan", "id": "zan", "name": "赞"},
            {"class": "bq-paishou", "id": "paishou", "name": "拍手"},
            {"class": "bq-ye", "id": "ye", "name": "耶"},
            {"class": "bq-woshou", "id": "woshou", "name": "握手"},
            {"class": "bq-baituo", "id": "baituo", "name": "拜托"},
            {"class": "bq-weixiao", "id": "weixiao", "name": "微笑"},
            {"class": "bq-ciya", "id": "ciya", "name": "呲牙"},
            {"class": "bq-touxiao", "id": "touxiao", "name": "偷笑"},
            {"class": "bq-yiwen", "id": "yiwen", "name": "疑问"},
            {"class": "bq-jingya", "id": "jingya", "name": "惊讶"},
            {"class": "bq-cahan", "id": "cahan", "name": "擦汗"},
            {"class": "bq-yun", "id": "yun", "name": "晕"},
            {"class": "bq-fennu", "id": "fennu", "name": "愤怒"},
            {"class": "bq-nanguo", "id": "nanguo", "name": "难过"},
            {"class": "bq-weiqu", "id": "weiqu", "name": "委屈"},
            {"class": "bq-liulei", "id": "liulei", "name": "流泪"},
            {"class": "bq-fendou", "id": "fendou", "name": "奋斗"},
            {"class": "bq-zhuakuang", "id": "zhuakuang", "name": "抓狂"},
            {"class": "bq-haixiu", "id": "haixiu", "name": "害羞"},
            {"class": "bq-deyi", "id": "deyi", "name": "得意"},
            {"class": "bq-shui", "id": "shui", "name": "睡"},
            {"class": "bq-aoman", "id": "aoman", "name": "傲慢"},
            {"class": "bq-jie", "id": "jie", "name": "饥饿"},
            {"class": "bq-kun", "id": "kun", "name": "困"},
            {"class": "bq-jingkong", "id": "jingkong", "name": "惊恐"},
            {"class": "bq-liuhan", "id": "spanuhan", "name": "流汗"},
            {"class": "bq-hanxiao", "id": "hanxiao", "name": "憨笑"},
            {"class": "bq-youxian", "id": "youxian", "name": "悠闲"},
            {"class": "bq-tu", "id": "tu", "name": "吐"},
            {"class": "bq-zhouma", "id": "zhouma", "name": "咒骂"},
            {"class": "bq-yukuai", "id": "yukuai", "name": "愉快"},
            {"class": "bq-xu", "id": "xu", "name": "嘘"},
            {"class": "bq-baiyan", "id": "baiyan", "name": "白眼"},
            {"class": "bq-fengle", "id": "fengle", "name": "疯了"},
            {"class": "bq-shuai", "id": "shuai", "name": "衰"},
            {"class": "bq-kulou", "id": "kulou", "name": "骷髅"},
            {"class": "bq-qiaoda", "id": "qiaoda", "name": "敲打"},
            {"class": "bq-zaijian","id": "zaijian","name": "再见"},
            {"class": "bq-tiaopi", "id": "tiaopi", "name": "调皮"},
            {"class": "bq-koubi", "id": "koubi", "name": "抠鼻"},
            {"class": "bq-guzhang", "id": "guzhang", "name": "鼓掌"},
            {"class": "bq-qiudale", "id": "qiudale", "name": "糗大了"},
            {"class": "bq-huaixiao", "id": "huaixiao", "name": "坏笑"},
            {"class": "bq-zuohengheng", "id": "zuohengheng", "name": "左哼哼"},
            {"class": "bq-youhengheng", "id": "youhengheng", "name": "右哼哼"},
            {"class": "bq-haqian", "id": "haqian", "name": "哈欠"},
            {"class": "bq-bishi", "id": "bishi", "name": "鄙视"},
            {"class": "bq-piezui", "id": "piezui", "name": "撇嘴"},
            {"class": "bq-kuaikule", "id": "kuaikule", "name": "快哭了"},
            {"class": "bq-yinxian", "id": "yinxian", "name": "阴险"},
            {"class": "bq-qinqin", "id": "qinqin", "name": "亲亲"},
            {"class": "bq-xia", "id": "xia", "name": "吓"},
            {"class": "bq-kelian", "id": "kespanan", "name": "可怜"},
            {"class": "bq-bizui", "id": "bizui", "name": "闭嘴"},
            {"class": "bq-daku", "id": "daku", "name": "大哭"},
            {"class": "bq-fadai", "id": "fadai", "name": "发呆"},
            {"class": "bq-ganga", "id": "ganga", "name": "尴尬"},
            {"class": "bq-ku", "id": "ku", "name": "酷"},
            {"class": "bq-lenghan", "id": "lenghan", "name": "冷汗"},
            {"class": "bq-se", "id": "se", "name": "色"},
            {"class": "bq-dabian", "id": "dabian", "name": "大便"}
        ]
        , emotions: [
            {"class": "emotion-a", "id": "0"},
            {"class": "emotion-b", "id": "1"},
            {"class": "emotion-c", "id": "2"},
            {"class": "emotion-d", "id": "3"},
            {"class": "emotion-e", "id": "4"},
            {"class": "emotion-f", "id": "5"},
            {"class": "emotion-g", "id": "6"},
            {"class": "emotion-h", "id": "7"},
            {"class": "emotion-i", "id": "8"},
            {"class": "emotion-j", "id": "9"},
            {"class": "emotion-k", "id": "10"},
            {"class": "emotion-l", "id": "11"},
            {"class": "emotion-m", "id": "12"},
            {"class": "emotion-n", "id": "13"},
            {"class": "emotion-o", "id": "14"},
            {"class": "emotion-p", "id": "15"}
        ]
    };

});